# Dev environment HTTP endpoints (routed via Traefik Ingress on localhost:8080)

# Heartbeat service
GET http://heartbeat.localhost:8080/heartbeat/17 HTTP/1.1

###

# IMDb readyz
GET http://imdb.localhost:8080/readyz HTTP/1.1

###

# IMDb healthz
GET http://imdb.localhost:8080/healthz HTTP/1.1

###

# IMDb healthz ietf
GET http://imdb.localhost:8080/healthz/ietf HTTP/1.1

###

# IMDb metrics
GET http://imdb.localhost:8080/metrics HTTP/1.1

###

# IMDb version
GET http://imdb.localhost:8080/version HTTP/1.1

###

# Swagger Home Page
GET http://imdb.localhost:8080 HTTP/1.1

###

# IMDb Movie API - retrieve list of actors and their profiles
GET http://imdb.localhost:8080/api/actors HTTP/1.1

###

# IMDb Movie API - retrieve profile of a specific actor by id
GET http://imdb.localhost:8080/api/actors/nm0000206 HTTP/1.1

###

# IMDb Movie API - retrieve profile of actors named Keanu
GET http://imdb.localhost:8080/api/actors?q=keanu HTTP/1.1

###

# IMDb Movie API - retrieve genres
GET http://imdb.localhost:8080/api/genres HTTP/1.1

###

# IMDb Movie API - retrieve movies
GET http://imdb.localhost:8080/api/movies HTTP/1.1

###

# IMDb Movie API - retrieve movie by id
GET http://imdb.localhost:8080/api/movies/tt0133093 HTTP/1.1

###

# IMDb Movie API - filter movies named Matrix
GET http://imdb.localhost:8080/api/movies?q=matrix HTTP/1.1

###

# IMDb Movie API - filter movies in the action genre
GET http://imdb.localhost:8080/api/movies?genre=action HTTP/1.1

###

# IMDb Movie API - filter movies released in 1999
GET http://imdb.localhost:8080/api/movies?year=1999 HTTP/1.1

###

# IMDb Movie API - filter movies with rating of 8.0
GET http://imdb.localhost:8080/api/movies?rating=8.0 HTTP/1.1

###
